/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author GBlue
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBarrack = new javax.swing.JButton();
        btnPillage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnLvHou = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sldLevelHouse = new javax.swing.JSlider();
        jTextField1 = new javax.swing.JTextField();
        pnLvWall = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        SldLevelWall = new javax.swing.JSlider();
        pnTypeHou = new javax.swing.JPanel();
        cbo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(253, 247, 221));
        setPreferredSize(new java.awt.Dimension(600, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(btnBarrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        add(btnPillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jPanel1.setBackground(new java.awt.Color(215, 172, 116));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 601, -1));

        pnLvHou.setBackground(new java.awt.Color(251, 232, 193));
        pnLvHou.setPreferredSize(new java.awt.Dimension(600, 50));
        pnLvHou.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Level of House");
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 20));
        pnLvHou.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, -1, 20));

        sldLevelHouse.setBackground(new java.awt.Color(251, 232, 193));
        sldLevelHouse.setMaximum(40);
        sldLevelHouse.setPreferredSize(new java.awt.Dimension(300, 20));
        pnLvHou.add(sldLevelHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 15, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(6, 20));
        pnLvHou.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 15, 60, -1));

        add(pnLvHou, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        pnLvWall.setBackground(new java.awt.Color(251, 232, 193));
        pnLvWall.setPreferredSize(new java.awt.Dimension(600, 50));
        pnLvWall.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Level Of Wall");
        pnLvWall.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, -1, -1));

        jTextField2.setText("jTextField1");
        pnLvWall.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 15, -1, -1));

        SldLevelWall.setBackground(new java.awt.Color(251, 232, 193));
        SldLevelWall.setMaximum(40);
        SldLevelWall.setPreferredSize(new java.awt.Dimension(300, 20));
        pnLvWall.add(SldLevelWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 15, -1, -1));

        add(pnLvWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        pnTypeHou.setBackground(new java.awt.Color(251, 232, 193));
        pnTypeHou.setPreferredSize(new java.awt.Dimension(600, 50));
        pnTypeHou.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbo.setBackground(new java.awt.Color(253, 247, 221));
        cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "My House", "My Ally", "Enemy", "Moor" }));
        cbo.setPreferredSize(new java.awt.Dimension(200, 20));
        pnTypeHou.add(cbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 15, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Type of House");
        pnTypeHou.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        add(pnTypeHou, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HouseInfo.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 190, 160));
        add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SldLevelWall;
    private javax.swing.JButton btnBarrack;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPillage;
    private javax.swing.JComboBox<String> cbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnLvHou;
    private javax.swing.JPanel pnLvWall;
    private javax.swing.JPanel pnTypeHou;
    private javax.swing.JSlider sldLevelHouse;
    // End of variables declaration//GEN-END:variables
}
